name: Terraform CI/CD for deploying AWS resource.
run-name: ${{ github.actor }} has triggered the pipeline

on:
  push: 
    branches: [ master ]

env: 
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  build-infra: 
    name: Terraform-ci-cd
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./aws-vpc-project
      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./aws-vpc-project    
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./aws-vpc-project
      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: ./aws-vpc-project  

             
